[#ftl]
[@addResourceGroupInformation
    type=SPA_COMPONENT_TYPE
    attributes=[]
    provider=AZURE_PROVIDER
    resourceGroup=DEFAULT_RESOURCE_GROUP
    services=
      [
        AZURE_NETWORK_FRONTDOOR_SERVICE,
        AZURE_STORAGE_SERVICE
      ]
/]