[#ftl]

[@addPseudoResourceProfile
    service=AZURE_AAD_APP_REGISTRATION_PSEUDO_SERVICE
    resource=AZURE_APPLICATION_REGISTRATION_RESOURCE_TYPE
/]

[@addPseudoResourceProfile
    service=AZURE_AAD_APP_REGISTRATION_PSEUDO_SERVICE
    resource=AZURE_APPLICATION_REGISTRATION_CLIENT_RESOURCE_TYPE
/]