[#ftl]
[@addResourceGroupInformation
    type=SQS_COMPONENT_TYPE
    attributes=[]
    provider=AZURE_PROVIDER
    resourceGroup=DEFAULT_RESOURCE_GROUP
    services=
        [
            AZURE_STORAGE_SERVICE
        ]
/]