[#ftl]

[#assign AZURE_DB_MYSQL_SERVER_RESOURCE_TYPE = "mysqlserver"]
[#assign AZURE_DB_MYSQL_SERVER_CONFIGURATION_RESOURCE_TYPE = "mysqlserverconfig"]
[#assign AZURE_DB_MYSQL_SERVER_DATABASE_RESOURCE_TYPE = "mysqldb"]
[#assign AZURE_DB_MYSQL_SERVER_FIREWALL_RULE_RESOURCE_TYPE = "mysqlfwrule"]
[#assign AZURE_DB_MYSQL_SERVER_SECURITY_ALERT_POLICY_RESOURCE_TYPE = "mysqlalertpolicy"]
[#assign AZURE_DB_MYSQL_SERVER_VNET_RULE_RESOURCE_TYPE = "mysqlvnetrule"]