[#ftl]

[#assign AZURE_DB_POSTGRES_SERVER_RESOURCE_TYPE = "postgresserver"]
[#assign AZURE_DB_POSTGRES_SERVER_CONFIGURATION_RESOURCE_TYPE = "postgresserverconfig"]
[#assign AZURE_DB_POSTGRES_SERVER_DATABASE_RESOURCE_TYPE = "postgresdb"]
[#assign AZURE_DB_POSTGRES_SERVER_FIREWALL_RULE_RESOURCE_TYPE = "postgresfwrule"]
[#assign AZURE_DB_POSTGRES_SERVER_SECURITY_ALERT_POLICY_RESOURCE_TYPE = "postgresalertpolicy"]
[#assign AZURE_DB_POSTGRES_SERVER_VNET_RULE_RESOURCE_TYPE = "postgresvnetrule"]